# Related Work {#work}

*Anything that inspired you, such as a paper, a web site, or something we discussed in class.*

------

In the past 10 years, there has been a lot of discussion around the benefits and risks of adopting electronic health records (EHR’s). Many news sources have covered the topic, and multiple government agencies have published recommendations and articles on the adoption of EHR’s. From 2008 to 2015, the number of office-based practitioners with EHR systems doubled, proving that the popularity of EHR’s are only increasing ([Healthit.gov](https://dashboard.healthit.gov/quickstats/pages/physician-ehr-adoption-trends.php)).

In 2011, the Centers for Medicare & Medicaid Services (CMS) initiated the Medicare and Medicaid Electronic Health Record Incentive Programs to encourage medical professionals to adopt EHR technology. The program includes incentives for different stages of implementation, including establishing EHR requirements, demonstrating meaningful use, and a final stage to demonstrate improved health outcomes that will start this year (2017).

The CMS provides millions of openly accessible data that they have used to evaluate the effectiveness of their incentive program. Looking through these data, we were inspired to utilize some of the R packages and tools that we have been learning in class, hoping to enable a better understanding of what types of providers enrolled in this incentive program are actually using EHR. Specifically, we wanted to implement the following course concepts:

1. Data Wrangling
+ [Import](https://github.com/datasciencelabs/2017/blob/master/lectures/wrangling/data-import.Rmd) and [combine](https://github.com/datasciencelabs/2017/blob/master/lectures/wrangling/combining-tables.Rmd) different sets of data in order to analyze relationships that have not been done before.
+ [Scrape](https://github.com/datasciencelabs/2017/blob/master/lectures/wrangling/web-scraping.Rmd) data directly off of websites outside of those related to CMS in order to analyze more than what they already have.

2. Visualization

+ Apply the [principles of data visualizations](https://github.com/datasciencelabs/2017/blob/master/lectures/dataviz/dataviz-principles.Rmd) to accurately and meaningfully present our statistical findings.
+ Create super cool while informative [plots](https://github.com/datasciencelabs/2017/blob/master/lectures/dataviz/gapminder.Rmd) to help visualize our exploratory analyses.

3. Statistical Analysis

+ Perform [regression analysis](https://github.com/datasciencelabs/2017/tree/master/lectures/regression) on the relationship between EHR use and provider demographics.
+ Report and interpret [statistical inference](https://github.com/datasciencelabs/2017/tree/master/lectures/inference) from our results.

