<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Electronic Health Records: Who Uses It?</title>
  <meta name="description" content="This is the final project report for BST 260 on the relationships between the use of Electronic Health Records (EHR) and provider demographics, separately among the eligible professionals (EPs) and eligible hospitals participating in the Medicare &amp; Medicaid EHR Incentive Program in 2016.">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="Electronic Health Records: Who Uses It?" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the final project report for BST 260 on the relationships between the use of Electronic Health Records (EHR) and provider demographics, separately among the eligible professionals (EPs) and eligible hospitals participating in the Medicare &amp; Medicaid EHR Incentive Program in 2016." />
  <meta name="github-repo" content="euniceyeh/EHR-Project" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Electronic Health Records: Who Uses It?" />
  
  <meta name="twitter:description" content="This is the final project report for BST 260 on the relationships between the use of Electronic Health Records (EHR) and provider demographics, separately among the eligible professionals (EPs) and eligible hospitals participating in the Medicare &amp; Medicaid EHR Incentive Program in 2016." />
  

<meta name="author" content="Eunice Yeh, Lauren Yoo, Katherine Wang">


<meta name="date" content="2017-12-11">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="questions.html">
<link rel="next" href="primary.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">BST 260 Final Project: EHR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Overview and Motivation</a></li>
<li class="chapter" data-level="2" data-path="work.html"><a href="work.html"><i class="fa fa-check"></i><b>2</b> Related Work</a></li>
<li class="chapter" data-level="3" data-path="questions.html"><a href="questions.html"><i class="fa fa-check"></i><b>3</b> Initial Questions</a></li>
<li class="chapter" data-level="4" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>4</b> Data</a><ul>
<li class="chapter" data-level="4.1" data-path="data.html"><a href="data.html#eligible-professionals-eps"><i class="fa fa-check"></i><b>4.1</b> Eligible Professionals (EPs)</a><ul>
<li class="chapter" data-level="4.1.1" data-path="data.html"><a href="data.html#sourcemetadata"><i class="fa fa-check"></i><b>4.1.1</b> Source/Metadata</a></li>
<li class="chapter" data-level="4.1.2" data-path="data.html"><a href="data.html#wrangling"><i class="fa fa-check"></i><b>4.1.2</b> Wrangling</a></li>
<li class="chapter" data-level="4.1.3" data-path="data.html"><a href="data.html#output"><i class="fa fa-check"></i><b>4.1.3</b> Output</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="data.html"><a href="data.html#eligible-hospitals-hosp"><i class="fa fa-check"></i><b>4.2</b> Eligible Hospitals (Hosp)</a><ul>
<li class="chapter" data-level="4.2.1" data-path="data.html"><a href="data.html#sourcemetadata-1"><i class="fa fa-check"></i><b>4.2.1</b> Source/Metadata</a></li>
<li class="chapter" data-level="4.2.2" data-path="data.html"><a href="data.html#wrangling-1"><i class="fa fa-check"></i><b>4.2.2</b> Wrangling</a></li>
<li class="chapter" data-level="4.2.3" data-path="data.html"><a href="data.html#output-1"><i class="fa fa-check"></i><b>4.2.3</b> Output</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data.html"><a href="data.html#vendors-products-ehr"><i class="fa fa-check"></i><b>4.3</b> Vendors &amp; Products (EHR)</a><ul>
<li class="chapter" data-level="4.3.1" data-path="data.html"><a href="data.html#sourcemetadata-2"><i class="fa fa-check"></i><b>4.3.1</b> Source/Metadata</a></li>
<li class="chapter" data-level="4.3.2" data-path="data.html"><a href="data.html#wrangling-2"><i class="fa fa-check"></i><b>4.3.2</b> Wrangling</a></li>
<li class="chapter" data-level="4.3.3" data-path="data.html"><a href="data.html#output-2"><i class="fa fa-check"></i><b>4.3.3</b> Output</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="primary.html"><a href="primary.html"><i class="fa fa-check"></i><b>5</b> Primary Analysis</a><ul>
<li class="chapter" data-level="5.1" data-path="primary.html"><a href="primary.html#physician-demographics"><i class="fa fa-check"></i><b>5.1</b> Physician Demographics</a><ul>
<li class="chapter" data-level="5.1.1" data-path="primary.html"><a href="primary.html#exploratory"><i class="fa fa-check"></i><b>5.1.1</b> Exploratory</a></li>
<li class="chapter" data-level="5.1.2" data-path="primary.html"><a href="primary.html#final-analysis"><i class="fa fa-check"></i><b>5.1.2</b> Final Analysis</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="primary.html"><a href="primary.html#hospital-demographics"><i class="fa fa-check"></i><b>5.2</b> Hospital Demographics</a><ul>
<li class="chapter" data-level="5.2.1" data-path="primary.html"><a href="primary.html#exploratory-analysis"><i class="fa fa-check"></i><b>5.2.1</b> Exploratory Analysis</a></li>
<li class="chapter" data-level="5.2.2" data-path="primary.html"><a href="primary.html#final-analysis-1"><i class="fa fa-check"></i><b>5.2.2</b> Final Analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="secondary.html"><a href="secondary.html"><i class="fa fa-check"></i><b>6</b> Secondary Analysis</a><ul>
<li class="chapter" data-level="6.1" data-path="secondary.html"><a href="secondary.html#by-geographical-regions"><i class="fa fa-check"></i><b>6.1</b> By Geographical Regions</a><ul>
<li class="chapter" data-level="6.1.1" data-path="secondary.html"><a href="secondary.html#physician-demographics-1"><i class="fa fa-check"></i><b>6.1.1</b> Physician Demographics</a></li>
<li class="chapter" data-level="6.1.2" data-path="secondary.html"><a href="secondary.html#hospital-demographics-1"><i class="fa fa-check"></i><b>6.1.2</b> Hospital Demographics</a></li>
<li class="chapter" data-level="6.1.3" data-path="secondary.html"><a href="secondary.html#regional-conclusions"><i class="fa fa-check"></i><b>6.1.3</b> Regional Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="secondary.html"><a href="secondary.html#by-ehr-vendors"><i class="fa fa-check"></i><b>6.2</b> By EHR Vendors</a><ul>
<li class="chapter" data-level="6.2.1" data-path="secondary.html"><a href="secondary.html#physician-demographics-2"><i class="fa fa-check"></i><b>6.2.1</b> Physician Demographics</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://katwang.github.io/BST-260-Final-Project-Site" target="blank">Our Project Website</a></li>
<li><a href="https://github.com/euniceyeh/EHR-Project" target="blank">Our Github Repo</a></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with Bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Electronic Health Records: Who Uses It?</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Data</h1>
<p>All of our data are based on the 2016 Medicare &amp; Medicaid EHR Incentive Program since the adoption of EHR is an ongoing basis: a provider who adopted and used EHR during the 2014 program, for example, is likely to still be in the program the following years. So theoretically, the 2016 program would be the most cumulative source of providers adopting EHR. As mentioned in <a href="https://euniceyeh.github.io/EHR-Project/work.html">Related Work</a>, the adoption of EHR has been consistently rising over the years across the U.S., so there is also no interest in looking at the use over time when we can just look at the latest collection of data. And since 2017 isn’t quite over yet, it wouldn’t be fair to start looking at the usage of EHR within the 2017 program, so the most recent completed data would be on the 2016 program.</p>
<div id="eligible-professionals-eps" class="section level2">
<h2><span class="header-section-number">4.1</span> Eligible Professionals (EPs)</h2>
<p>To answer the first of our <a href="https://euniceyeh.github.io/EHR-Project/questions.html">Initial Questions</a> as to whether or not a physician’s age, education, practice location, etc. may be related to their use of EHR in the incentive program, we must be able to find demographics data at the practitioner level.</p>
<div id="sourcemetadata" class="section level3">
<h3><span class="header-section-number">4.1.1</span> Source/Metadata</h3>
<p>And here we are: readily available on <a href="https://data.medicare.gov/Physician-Compare/Physician-Compare-National-Downloadable-File/mj5m-pzi6">Data.Medicare.gov</a> are the demographics of physicians eligible for the Medicare &amp; Medicaid EHR incentive program at the practitioner level. We used the API link to read in the data set and applied SQL filtering options to speed up the download since it is a large file. We specified the limit to be exactly 2254703 because that’s the exact number of rows the data contain, if we don’t specify this, the default limit of rows that get downloaded is 100. To compensate, we will specify the exact columns of interest to include, which can also be specified in the download link (we looked through the metadata on the website to select the meaningful and interesting variables).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">dat &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://data.medicare.gov/resource/c8qv-268j.csv?$limit=2254703&amp;$select=npi,frst_nm,gndr,cred,med_sch,grd_yr,pri_spec,cty,st,zip,hosp_afl_1,hosp_afl_lbn_1,ehr&amp;$order=npi&quot;</span>)
<span class="kw">saveRDS</span>(dat, <span class="st">&quot;./data/dat_raw.rds&quot;</span>) <span class="co"># saving data for reproducibility</span></code></pre></div>
</div>
<div id="wrangling" class="section level3">
<h3><span class="header-section-number">4.1.2</span> Wrangling</h3>
<p>Let’s first take a look at the data structure and a summary of all the columns.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(dat)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    1527291 obs. of  13 variables:
##  $ cred          : Factor w/ 22 levels &quot;&quot;,&quot;AA&quot;,&quot;AU&quot;,&quot;CNA&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ cty           : Factor w/ 10192 levels &quot;20850&quot;,&quot;ABBEVILLE&quot;,..: 2345 274 7938 2790 9076 1041 5545 5545 364 364 ...
##  $ ehr           : Factor w/ 2 levels &quot;&quot;,&quot;Y&quot;: 1 1 1 1 2 1 1 1 1 1 ...
##  $ frst_nm       : Factor w/ 54156 levels &quot;A&quot;,&quot;A&#39;LANNE&quot;,..: 3360 3360 3360 48311 38890 10170 20706 20706 24158 24158 ...
##  $ gndr          : Factor w/ 3 levels &quot;F&quot;,&quot;M&quot;,&quot;U&quot;: 2 2 2 2 2 2 1 1 2 2 ...
##  $ grd_yr        : int  1994 1994 1994 2003 1999 2003 2007 2007 1997 1997 ...
##  $ hosp_afl_1    : Factor w/ 4746 levels &quot;&quot;,&quot;010001&quot;,&quot;010005&quot;,..: 4371 4371 4371 1112 3220 3617 3168 3168 622 622 ...
##  $ hosp_afl_lbn_1: Factor w/ 4515 levels &quot;&quot;,&quot;ABBEVILLE AREA MEDICAL CENTER&quot;,..: 2020 2020 2020 1127 2405 2967 1943 1943 4203 4203 ...
##  $ med_sch       : Factor w/ 398 levels &quot;A T STILL UN, ARIZONA SCHL OF DENT.Y &amp; ORAL HLTH&quot;,..: 215 215 215 321 215 223 261 261 209 209 ...
##  $ npi           : int  1003000126 1003000126 1003000126 1003000134 1003000142 1003000407 1003000423 1003000423 1003000480 1003000480 ...
##  $ pri_spec      : Factor w/ 83 levels &quot;&quot;,&quot;ADDICTION MEDICINE&quot;,..: 38 38 38 61 5 24 51 51 27 27 ...
##  $ st            : Factor w/ 56 levels &quot;&quot;,&quot;AK&quot;,&quot;AL&quot;,&quot;AR&quot;,..: 50 50 50 17 39 42 39 39 7 7 ...
##  $ zip           : Factor w/ 188675 levels &quot;&quot;,&quot;000075949&quot;,..: 43170 47812 50388 117622 89610 35299 90294 90294 150777 150777 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(dat)</code></pre></div>
<pre><code>##       cred                   cty          ehr            frst_nm       
##         :1012568   HOUSTON     :  25754    :1194451   MICHAEL:  30701  
##  MD     : 344822   PITTSBURGH  :  25135   Y: 332840   DAVID  :  27486  
##  PA     :  29223   NEW YORK    :  18521               JOHN   :  27117  
##  NP     :  25666   PHILADELPHIA:  18025               ROBERT :  21989  
##  DO     :  21639   CHICAGO     :  16532               JAMES  :  20402  
##  CNA    :  16635   ANN ARBOR   :  16390               (Other):1399580  
##  (Other):  76738   (Other)     :1406934               NA&#39;s   :     16  
##  gndr           grd_yr       hosp_afl_1     
##  F:681413   Min.   :1942          : 449488  
##  M:845877   1st Qu.:1988   230046 :  13889  
##  U:     1   Median :1999   450076 :   7003  
##             Mean   :1997   490009 :   5784  
##             3rd Qu.:2008   390111 :   5496  
##             Max.   :2017   050454 :   5261  
##             NA&#39;s   :4024   (Other):1040370  
##                                             hosp_afl_lbn_1   
##                                                    : 450721  
##  UNIVERSITY OF MICHIGAN HEALTH SYSTEM              :  13889  
##  UNIVERSITY OF TEXAS M D ANDERSON CANCER CENTER,THE:   7003  
##  UNIVERSITY OF VIRGINIA MEDICAL CENTER             :   5784  
##  HOSPITAL OF UNIV OF PENNSYLVANIA                  :   5496  
##  UCSF MEDICAL CENTER                               :   5261  
##  (Other)                                           :1039137  
##                                          med_sch            npi           
##  OTHER                                       :771781   Min.   :1.003e+09  
##  WAYNE STATE UNIVERSITY SCHOOL OF MEDICINE   : 11559   1st Qu.:1.165e+09  
##  INDIANA UNIVERSITY SCHOOL OF MEDICINE       : 10794   Median :1.337e+09  
##  PHILADELPHIA COLLEGE OF OSTEOPATHIC MEDICINE: 10036   Mean   :1.340e+09  
##  TEMPLE UNIVERSITY SCHOOL OF MEDICINE        :  9473   3rd Qu.:1.509e+09  
##  UNIVERSITY OF MINNESOTA MEDICAL SCHOOL      :  9266   Max.   :1.680e+09  
##  (Other)                                     :704382                      
##                  pri_spec            st                zip         
##  NURSE PRACTITIONER  :148237   CA     :131284   481095000:  14678  
##  INTERNAL MEDICINE   :141051   TX     :114489   152124756:   6601  
##  FAMILY PRACTICE     :119255   PA     :100942   770304000:   6033  
##  PHYSICIAN ASSISTANT :111992   NY     : 95038   229080001:   4827  
##  PHYSICAL THERAPY    : 69682   FL     : 84422   326103003:   4336  
##  DIAGNOSTIC RADIOLOGY: 64327   MI     : 66982   110303816:   3727  
##  (Other)             :872747   (Other):934134   (Other)  :1487089</code></pre>
<p>Observations from the above output:</p>
<ul>
<li>There are 56 levels of states, which means this data include states outside of the 50 mainland states and DC. Since we don’t have sufficient data on the Virgin Islands and Guam, we will have to filter these states out.</li>
<li>There is one person whose gender is unknown, we will filter this person out since we want to group by gender.</li>
<li>There are 4024 rows with missing graduation years, will need to filer this out too if graduation years is one of the main demographics of interest (will mess up plotting). Also, one or more physician who graduated in 2017 slipped into our data…we will ignore this by filtering it out too.</li>
<li>It looks like most zip codes in this data are the full 9-digit zip codes, which can be split into the standard 5-digit format and the 4-digit.</li>
<li>There are way too many levels of medical schools and primary specialties, we will probably focus on looking at the most popular ones during exploratory analysis rather than the final primary analysis.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&quot;state&quot;</span>)
clean &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(st <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(state.abb, <span class="st">&quot;DC&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(gndr <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;F&quot;</span>, <span class="st">&quot;M&quot;</span>) <span class="op">&amp;</span><span class="st"> </span><span class="op">!</span><span class="kw">is.na</span>(grd_yr) <span class="op">&amp;</span><span class="st"> </span>grd_yr <span class="op">!=</span><span class="st"> </span><span class="dv">2017</span>)</code></pre></div>
<p>Now we only have 51 levels of states, 2 levels of gender, and no records with missing graduation year. To make sure we only keep valid zip codes, we can try to use R’s zip code package to validate our zip codes. This is important because we want to be able to accurately perform our analyses on the location variables and regional analysis (especially zip code plotting).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># separate out the first five zip codes from the last four extension</span>
clean &lt;-<span class="st"> </span>clean <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">zip.ext =</span> <span class="kw">substr</span>(<span class="kw">as.character</span>(zip), <span class="dv">6</span>, <span class="dv">9</span>), 
                          <span class="dt">zip =</span> <span class="kw">substr</span>(<span class="kw">as.character</span>(zip), <span class="dv">1</span>, <span class="dv">5</span>))

<span class="co"># use R zipcode package and data</span>
<span class="kw">library</span>(zipcode)
<span class="kw">data</span>(<span class="st">&quot;zipcode&quot;</span>)
zip_dat &lt;-<span class="st"> </span>clean <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">left_join</span>(zipcode,<span class="dt">by=</span><span class="st">&#39;zip&#39;</span>) 

<span class="co"># check state mismatches</span>
zip_mismatch &lt;-<span class="st"> </span>zip_dat <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">st =</span> <span class="kw">as.character</span>(st)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(st <span class="op">!=</span><span class="st"> </span>state) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(npi, frst_nm, zip, cty, city, st, state, latitude, longitude)

<span class="co"># check number of records mismatched</span>
<span class="kw">nrow</span>(zip_mismatch)</code></pre></div>
<pre><code>## [1] 1034</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># look at the top five mismatches</span>
(top5_mismatch &lt;-<span class="st"> </span>zip_mismatch <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(zip, cty, st, city, state) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">n =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(n)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">head</span>(<span class="dv">5</span>))</code></pre></div>
<pre><code>## # A tibble: 5 x 6
## # Groups:   zip, cty, st, city [5]
##     zip            cty    st           city state     n
##   &lt;chr&gt;         &lt;fctr&gt; &lt;chr&gt;          &lt;chr&gt; &lt;chr&gt; &lt;int&gt;
## 1 99362    WALLA WALLA    WA    Walla Walla    OR   222
## 2 52761      MUSCATINE    IA      Muscatine    IL   114
## 3 43530        GRANGER    IN         Jewell    OH    86
## 4 22401 FREDERICKSBURG    MD Fredericksburg    VA    82
## 5 20176        HANOVER    MD       Leesburg    VA    74</code></pre>
<p>In order to not just blatantly throw away 1034 mismatches, we will look at the top 5 most common mismatches on a case-by-case basis to try to salvage as many records as possible without searching too deeply in our data set. Also, starting from the 6th most common mismatches, the number of records <code>n</code> were down to 58 or less, so they would have little effect on the data set.</p>
<p>The results of searching up the top 10 mismatches on Google Maps:</p>
<ul>
<li>The zip code 99362 spans across Walla Walla in both WA and OR, so it is likely that the practice is located on the WA side of the zip code coverage. We will ignore the state mismatch from the zip code package for this case.</li>
<li>The zip code 52761 does belong to Muscatine, IA, which is right on the border of IL. Again, the practice is most likely located on the IA side. Will ignore the state mismatch for this case as well.</li>
<li>The zip code for Granger, IN was most likely mistyped. The correct zip code for Granger is 46530, which is very close to 43530. We will fix the zip code for this particular case only.</li>
<li>The zip code 22401 does belong to Frederickburg, VA, and is not near the border of VA and MD at all. There is a “Frederick” city in MD, but none of its zip codes look similar enough to 22401. No clear culprit, will have to let this one go. :(</li>
<li>The zip code for Hanover, MD is 21076, which was most likely mistyped as 20176. We will fix this particular case as well.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># leave out the 22401 Fredericksburg MD mismatch, fix the zip codes for Granger and Hanover.</span>
zip_fix &lt;-<span class="st"> </span>top5_mismatch <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(cty <span class="op">!=</span><span class="st"> &#39;FREDERICKSBURG&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">zip =</span> <span class="kw">replace</span>(zip, zip <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">43530</span>, <span class="dv">20176</span>), <span class="kw">c</span>(<span class="dv">46530</span>, <span class="dv">21076</span>))) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>n)

mismatch_tokeep &lt;-<span class="st"> </span>zip_dat <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>zip) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># we want to replace the original wrong zip codes with the fixed zip codes</span>
<span class="st">  </span><span class="kw">inner_join</span>(zip_fix, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&#39;cty&#39;</span>,<span class="st">&#39;st&#39;</span>, <span class="st">&#39;city&#39;</span>, <span class="st">&#39;state&#39;</span>))</code></pre></div>
<pre><code>## Warning: Column `st` joining factor and character vector, coercing into
## character vector</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">clean &lt;-<span class="st"> </span>zip_dat <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">st =</span> <span class="kw">as.character</span>(st), <span class="dt">state =</span> <span class="kw">as.character</span>(state)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(st <span class="op">==</span><span class="st"> </span>state <span class="op">|</span><span class="st"> </span><span class="kw">nchar</span>(zip) <span class="op">==</span><span class="st"> </span><span class="dv">5</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># keeping only the matches</span>
<span class="st">  </span><span class="kw">bind_rows</span>(mismatch_tokeep) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># then add in the mismatches we wanted to keep or have fixed</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>city, <span class="op">-</span>state) <span class="co"># will rely on the original city and state columns</span></code></pre></div>
<p>Continuing on with our wrangling…</p>
<ul>
<li>About 29.4304098% of the (original) data are of physicians not affiliated with any hospital, these are the practitioners we will subset on to do our practitioner-level analysis on since these are the only cases when a physician’s demographics can have an effect on the choice of using EHR. For physicians who are affiliated with a hospital, their demographics would no longer be informative as to whether or not they use EHR, it would then have to be the demographics of the hospitals that could inform the use of EHR at the hospital-level. Thus, we were able to find demographics on hospitals across the U.S. in general, which will be discussed in the next section within this chapter, but there’s no indication of participation in the incentive program nor EHR use, so we will have to merge that hospital demographic data with the practitioners in this data set who are affiliated with any one hospital.</li>
</ul>
<p>So for the practitioner-level analysis we want to:</p>
<ul>
<li>Calculate the number of years since graduation</li>
<li>Use 1’s and 0’s instead of ‘Y’ and blanks as indicator of EHR use for our binary outcome</li>
<li>Keep only one record per physician, which means we would have to lose the distinct practice locations for physicians who have multiple practices. But since we can’t fit our logistic model with either city, state, or zip code, there’s no point in keeping this detail. Instead, we can calculate the number of distinct practices these physicians have in order to collapse the data to the practitioner level.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EPs &lt;-<span class="st"> </span>clean <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(hosp_afl_<span class="dv">1</span> <span class="op">==</span><span class="st"> &#39;&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">yrs_grd =</span> <span class="dv">2016</span> <span class="op">-</span><span class="st"> </span><span class="kw">as.integer</span>(grd_yr), <span class="co"># calc the n of years since graduation</span>
         <span class="dt">cred =</span> <span class="kw">case_when</span>(cred <span class="op">==</span><span class="st"> &#39;&#39;</span> <span class="op">~</span><span class="st"> &#39;NA&#39;</span>, <span class="co"># assign blanks to NA&#39;s</span>
                          <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="kw">as.character</span>(cred)),
         <span class="dt">cred =</span> <span class="kw">as.factor</span>(cred),
         <span class="dt">ehr =</span> <span class="kw">case_when</span>(ehr <span class="op">==</span><span class="st"> &#39;Y&#39;</span> <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="co"># use numeric indicators</span>
                         ehr <span class="op">==</span><span class="st"> &#39;&#39;</span> <span class="op">~</span><span class="st"> </span><span class="dv">0</span>),
         <span class="dt">ehr =</span> <span class="kw">as.factor</span>(ehr)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>hosp_afl_<span class="dv">1</span>, <span class="op">-</span>hosp_afl_lbn_<span class="dv">1</span>, <span class="op">-</span>frst_nm) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">distinct</span>(npi, <span class="dt">.keep_all =</span> <span class="ot">TRUE</span>) <span class="co"># keep only one row per physician</span>

<span class="co"># calculate the number of practices for each physician</span>
SL &lt;-<span class="st"> </span>dat <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(npi) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="dt">locations =</span> <span class="kw">n_distinct</span>(zip))

EPs &lt;-<span class="st"> </span><span class="kw">left_join</span>(EPs, SL, <span class="dt">by=</span><span class="st">&quot;npi&quot;</span>)

<span class="kw">rm</span>(SL)
<span class="kw">summary</span>(EPs)</code></pre></div>
<pre><code>##       cred                 cty         ehr        gndr      
##  NA     :167692   NEW YORK   :  3555   0:214471   F:128382  
##  MD     : 19334   HOUSTON    :  1875   1: 18284   M:104373  
##  DC     :  9698   BROOKLYN   :  1701              U:     0  
##  PT     :  6881   LOS ANGELES:  1700                        
##  OD     :  6773   CHICAGO    :  1586                        
##  CSW    :  5750   PHOENIX    :  1490                        
##  (Other): 16627   (Other)    :220848                        
##      grd_yr                                         med_sch      
##  Min.   :1942   OTHER                                   :140789  
##  1st Qu.:1988   PALMER COLLEGE CHIROPRACTIC - DAVENPORT :  4547  
##  Median :1999   LOGAN COLLEGE OF CHIROPRACTIC           :  2312  
##  Mean   :1997   PENNSYLVANIA COLLEGE OF OPTOMETRY       :  2310  
##  3rd Qu.:2009   SOUTHERN COLLEGE OF OPTOMETRY           :  2211  
##  Max.   :2016   ILLINOIS COLLEGE OF OPTOMETRY AT CHICAGO:  2184  
##                 (Other)                                 : 78402  
##       npi                              pri_spec          st           
##  Min.   :1.003e+09   PHYSICAL THERAPY      :34788   Length:232755     
##  1st Qu.:1.165e+09   CHIROPRACTIC          :27033   Class :character  
##  Median :1.336e+09   CLINICAL SOCIAL WORKER:25225   Mode  :character  
##  Mean   :1.340e+09   NURSE PRACTITIONER    :22163                     
##  3rd Qu.:1.509e+09   OPTOMETRY             :20352                     
##  Max.   :1.680e+09   CLINICAL PSYCHOLOGIST :16522                     
##                      (Other)               :86672                     
##      zip              zip.ext             latitude       longitude      
##  Length:232755      Length:232755      Min.   :19.10   Min.   :-170.27  
##  Class :character   Class :character   1st Qu.:34.14   1st Qu.: -98.57  
##  Mode  :character   Mode  :character   Median :39.40   Median : -86.18  
##                                        Mean   :38.19   Mean   : -91.39  
##                                        3rd Qu.:41.75   3rd Qu.: -77.34  
##                                        Max.   :66.90   Max.   : -67.24  
##                                        NA&#39;s   :140     NA&#39;s   :140      
##     yrs_grd        locations      
##  Min.   : 0.00   Min.   :  1.000  
##  1st Qu.: 7.00   1st Qu.:  1.000  
##  Median :17.00   Median :  1.000  
##  Mean   :18.55   Mean   :  1.293  
##  3rd Qu.:28.00   3rd Qu.:  1.000  
##  Max.   :74.00   Max.   :359.000  
## </code></pre>
</div>
<div id="output" class="section level3">
<h3><span class="header-section-number">4.1.3</span> Output</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># permanently save physician-level analysis dataset to repo</span>
<span class="kw">saveRDS</span>(EPs, <span class="dt">file =</span> <span class="st">&quot;./data/EPs.rds&quot;</span>)

<span class="co"># for the rest of practitioners who are affiliated with a hospital</span>
hosp_afl &lt;-<span class="st"> </span>clean <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># filter on the clean version</span>
<span class="st">  </span><span class="kw">filter</span>(hosp_afl_<span class="dv">1</span> <span class="op">!=</span><span class="st"> &#39;&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">hosp_afl_lbn_1 =</span> <span class="kw">as.character</span>(hosp_afl_lbn_<span class="dv">1</span>), 
         <span class="dt">cty =</span> <span class="kw">str_trim</span>(<span class="kw">as.character</span>(cty)),
         <span class="dt">st =</span> <span class="kw">as.character</span>(st),
         <span class="dt">ehr =</span> <span class="kw">ifelse</span>(ehr <span class="op">==</span><span class="st"> &quot;Y&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="co"># only keep relevant or potentially interesting variables (keeping npi to count number of physicians)</span>
<span class="st">  </span><span class="kw">distinct</span>(npi, hosp_afl_lbn_<span class="dv">1</span>, st, cty, ehr, hosp_afl_<span class="dv">1</span>, pri_spec, gndr, grd_yr)

<span class="co"># clean up intermediate data sets</span>
<span class="kw">rm</span>(dat, clean, zipcode, zip_dat, zip_fix, zip_mismatch, mismatch_tokeep, top5_mismatch)</code></pre></div>
<ul>
<li>We are storing the <code>EPs</code> data set as a <code>.rds</code> file in our repo under the <code>/data</code> directory for reproducibility of our analysis since this is the clean analysis-ready data set that will be used to analyze the potential effects of practitioner demographics on EHR use in our <a href="https://euniceyeh.github.io/EHR-Project/primary.html">Primary Analysis</a>.</li>
<li>The <code>hosp_afl</code> data set, still containing one row per physician per hospital location, is to be merged with the hospital demographics data discussed in the next section.</li>
<li>Both <code>EPs</code> and the merged-to-be data of <code>hosp_afl</code> containing the hospital demographics are to be merged with the <a href="https://euniceyeh.github.io/EHR-Project/data.html#vendors-products-ehr"><code>EHR</code></a> vendor and product information in the last section of this chapter, in order to explore both physician and hospital demographics by specific types of EHR used.</li>
</ul>
</div>
</div>
<div id="eligible-hospitals-hosp" class="section level2">
<h2><span class="header-section-number">4.2</span> Eligible Hospitals (Hosp)</h2>
<p>General hospital demographics such as the total number of staffed beds, total number of discharges, total number of patient days, and total gross patient revenue (inpatient and outpatient) are all publicly accessible on the <a href="https://www.ahd.com/states/">American Hospital Directory</a> organized by U.S. states. Since there is not a <code>.csv</code> file ready for us to download and the hospital demographics are already neatly summarized in a table for each state, we decided that we could do some web scraping for this.</p>
<div id="sourcemetadata-1" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Source/Metadata</h3>
<p>The link to each U.S. state’s summary table of hospital demographics by hospital name in that state begins with the same URL: <code>https://www.ahd.com/states/hospital_</code> and ends with the state’s abbreviation plus a <code>.html</code>. For example, a table of hospital demographics for each hospital in Massachusetts can be directly scraped from the link, <a href="https://www.ahd.com/states/hospital_MA.html" class="uri">https://www.ahd.com/states/hospital_MA.html</a>. The details of these hospital statistics are described <a href="https://www.ahd.com/definitions/statistics.html">here</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">hosp_web &lt;-<span class="st"> </span><span class="kw">data.frame</span>()
<span class="cf">for</span> (st <span class="cf">in</span>  <span class="kw">c</span>(state.abb, <span class="st">&quot;DC&quot;</span>)){
  url =<span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;https://www.ahd.com/states/hospital_&quot;</span>, st, <span class="st">&quot;.html&quot;</span>, <span class="dt">sep=</span><span class="st">&#39;&#39;</span>)
  st_df &lt;-<span class="st"> </span><span class="kw">read_html</span>(url) <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">html_nodes</span>(<span class="st">&quot;table&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">    </span>.[[<span class="dv">2</span>]] <span class="op">%&gt;%</span>
<span class="st">    </span><span class="kw">html_table</span>()
  st_df &lt;-<span class="st"> </span><span class="kw">as.data.frame.matrix</span>(<span class="kw">eval</span>(<span class="kw">parse</span>(<span class="dt">text=</span>st)))
  <span class="co"># removing the TOTAL row at the end of each table</span>
  st_df &lt;-<span class="st"> </span>st_df[<span class="op">!</span>(st_df<span class="op">$</span><span class="st">&quot;Hospital Name&quot;</span><span class="op">==</span><span class="st">&quot;T O T A L&quot;</span>),]
  st_df<span class="op">$</span>State &lt;-<span class="st"> </span>st
  hosp_web &lt;-<span class="st"> </span><span class="kw">rbind</span>(hosp_web, st_df)
}
<span class="kw">saveRDS</span>(hosp_web, <span class="st">&quot;./data/hosp_raw.rds&quot;</span>) <span class="co"># saving data for reproducibility</span></code></pre></div>
</div>
<div id="wrangling-1" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Wrangling</h3>
<p>Let’s take a look at the data structure of the raw scrapped hospital demographics.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(hosp_web)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    3907 obs. of  7 variables:
##  $ Hospital_name        : chr  &quot;Alaska Native Medical Center&quot; &quot;Alaska Regional Hospital&quot; &quot;Bartlett Regional Hospital&quot; &quot;Central Peninsula General Hospital&quot; ...
##  $ City                 : chr  &quot;Anchorage&quot; &quot;Anchorage&quot; &quot;Juneau&quot; &quot;Soldotna&quot; ...
##  $ Staffed_beds         : chr  &quot;152&quot; &quot;174&quot; &quot;57&quot; &quot;106&quot; ...
##  $ Total_discharges     : chr  &quot;7,320&quot; &quot;6,405&quot; &quot;1,710&quot; &quot;2,575&quot; ...
##  $ Patient_days         : chr  &quot;38,687&quot; &quot;33,507&quot; &quot;6,325&quot; &quot;10,186&quot; ...
##  $ Gross_patient_revenue: chr  &quot;$0&quot; &quot;$947,754&quot; &quot;$147,231&quot; &quot;$305,469&quot; ...
##  $ State                : chr  &quot;AK&quot; &quot;AK&quot; &quot;AK&quot; &quot;AK&quot; ...</code></pre>
<p>To do:</p>
<ul>
<li>We need to turn all the demographic information into numeric columns so we can use them as continuous variables.</li>
<li>These values are reported with commas, so we need to strip these out.</li>
<li>All the gross patient revenues are reported with a dollar sign in addition to the commas, so we need to strip those out too.</li>
<li>Proper cases are harder to match on, will convert all letters in city and hospital name to upper case.</li>
<li>It looks like some hospital has a gross patient revenue of $0…is this possible? Will explore this after dealing with all of the above first.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">hosp_clean &lt;-<span class="st"> </span><span class="kw">transform</span>(hosp_web, 
                       <span class="dt">Staffed_beds =</span> <span class="kw">as.numeric</span>(<span class="kw">gsub</span>(<span class="st">&quot;,&quot;</span>, <span class="st">&quot;&quot;</span>, Staffed_beds)), 
                       <span class="dt">Total_discharges =</span> <span class="kw">as.numeric</span>(<span class="kw">gsub</span>(<span class="st">&quot;,&quot;</span>, <span class="st">&quot;&quot;</span>, Total_discharges)),
                       <span class="dt">Patient_days =</span> <span class="kw">as.numeric</span>(<span class="kw">gsub</span>(<span class="st">&quot;,&quot;</span>,<span class="st">&quot;&quot;</span>, Patient_days)),
                       <span class="dt">Gross_patient_revenue =</span> <span class="kw">as.numeric</span>(<span class="kw">gsub</span>(<span class="st">&quot;</span><span class="ch">\\</span><span class="st">$|,&quot;</span>, <span class="st">&quot;&quot;</span>, Gross_patient_revenue)),
                       <span class="dt">Hospital_name =</span> <span class="kw">toupper</span>(Hospital_name),
                       <span class="dt">City =</span> <span class="kw">toupper</span>(<span class="kw">str_trim</span>(<span class="kw">as.character</span>(City)))
                       )
<span class="kw">summary</span>(hosp_clean)</code></pre></div>
<pre><code>##  Hospital_name          City            Staffed_beds     Total_discharges
##  Length:3907        Length:3907        Min.   :    0.0   Min.   :     0  
##  Class :character   Class :character   1st Qu.:   48.0   1st Qu.:  1244  
##  Mode  :character   Mode  :character   Median :  133.0   Median :  4562  
##                                        Mean   :  204.8   Mean   :  8017  
##                                        3rd Qu.:  264.0   3rd Qu.: 11336  
##                                        Max.   :36985.0   Max.   :136646  
##   Patient_days    Gross_patient_revenue    State          
##  Min.   :     0   Min.   :       0      Length:3907       
##  1st Qu.:  4104   1st Qu.:   98340      Class :character  
##  Median : 18892   Median :  377425      Mode  :character  
##  Mean   : 37794   Mean   :  797958                        
##  3rd Qu.: 51621   3rd Qu.: 1001421                        
##  Max.   :695643   Max.   :15618749</code></pre>
<p>It looks like the zero value wasn’t just for the gross patient revenue. From the summary output, we can see that the minimum values on all hospital demographics (staffed beds, total discharges, patient days, gross patient revenue) are zero, which doesn’t seem right. Theoretically, it is impossible for any <em>functioning</em> hospital to have a <em>total</em> of zero on any of these characteristics. Would having a total of zero number of staffed beds really make it a hospital? Can a hospital survive on a gross patient revenue of zero dollars? We thought that it might be a web scrapping error, but when we went back and looked on the website, some of their tables definitely have random zero hospital statistics and some even have a whole row of zeros for certain hospitals. The metadata wasn’t very clear on this, but it seems like it is their way of representing missing data. Instead of keeping them as zeros, which would affect any computation we want to perform on these continuous variables, we will convert every zero into a true missing value, <code>NA</code>. But if a hospital has all missing demographics (the entire row of zeros), then we will just remove that hospital entirely (delete the whole row).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># the demographics are columns 3 to 6 of the data frame</span>
<span class="kw">is.na</span>(hosp_clean[,<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>]) &lt;-<span class="st"> </span><span class="op">!</span>hosp_clean[,<span class="dv">3</span><span class="op">:</span><span class="dv">6</span>] <span class="co"># turn 0&#39;s to NAs</span>
hosp_clean &lt;-<span class="st"> </span>hosp_clean[<span class="kw">rowSums</span>(<span class="kw">is.na</span>(hosp_clean)) <span class="op">&lt;</span><span class="st"> </span><span class="dv">4</span>,] <span class="co"># only delete hosp with all four NAs</span>
<span class="kw">summary</span>(hosp_clean)</code></pre></div>
<pre><code>##  Hospital_name          City            Staffed_beds     Total_discharges
##  Length:3456        Length:3456        Min.   :    1.0   Min.   :     1  
##  Class :character   Class :character   1st Qu.:   73.0   1st Qu.:  2141  
##  Mode  :character   Mode  :character   Median :  157.0   Median :  5692  
##                                        Mean   :  231.6   Mean   :  9087  
##                                        3rd Qu.:  290.0   3rd Qu.: 12564  
##                                        Max.   :36985.0   Max.   :136646  
##                                        NA&#39;s   :1         NA&#39;s   :9       
##   Patient_days    Gross_patient_revenue    State          
##  Min.   :     1   Min.   :    2298      Length:3456       
##  1st Qu.:  7740   1st Qu.:  188177      Class :character  
##  Median : 23922   Median :  504646      Mode  :character  
##  Mean   : 42838   Mean   :  923192                        
##  3rd Qu.: 57391   3rd Qu.: 1149258                        
##  Max.   :695643   Max.   :15618749                        
##  NA&#39;s   :9        NA&#39;s   :79</code></pre>
<p>Now the minimum value is 1…still questionable and potentially causing the skew in their distributions. But we did take a look at these specific hospitals with any one demographic characteristic of value 1 and they seem to also have low values of the other characteristics as well (not necessarily exactly of 1, that would’ve been even more suspicious), so these may very well be valid who knows. Anyway, we need to move on with our lives, I mean, to merging with <code>hosp_afl</code> (which is a subset of practitioners who are affiliated with a hospital from the previous section) on the hospital name and state since different hospitals in different locations can have the same name. Since <code>hosp_afl</code> can have multiple rows per hospital if more than one physician in the data is affiliated with it, so we will aggregate the data back to hospital-level after the merge by summarizing physician-level information.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">hosps &lt;-<span class="st"> </span><span class="kw">inner_join</span>(hosp_clean, hosp_afl, <span class="dt">by=</span><span class="kw">c</span>(<span class="st">&quot;Hospital_name&quot;</span>=<span class="st">&quot;hosp_afl_lbn_1&quot;</span>, <span class="st">&quot;State&quot;</span>=<span class="st">&quot;st&quot;</span>))
hosps &lt;-<span class="st"> </span>hosps <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(hosp_afl_<span class="dv">1</span>, Hospital_name, State, Staffed_beds, Total_discharges, Patient_days, Gross_patient_revenue) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num_phys =</span> <span class="kw">n_distinct</span>(npi),
            <span class="dt">female_prop =</span> <span class="kw">round</span>(<span class="kw">mean</span>(<span class="kw">ifelse</span>(gndr <span class="op">==</span><span class="st"> &quot;F&quot;</span>, <span class="dv">1</span>, <span class="dv">0</span>)),<span class="dv">2</span>), 
            <span class="dt">avg_grad_year =</span> <span class="kw">round</span>(<span class="kw">mean</span>(grd_yr),<span class="dv">2</span>),
            <span class="dt">n_specialty =</span><span class="kw">n_distinct</span>(pri_spec),
            <span class="dt">EHR_use =</span> <span class="kw">as.factor</span>(<span class="kw">max</span>(ehr)))
<span class="kw">summary</span>(hosps)</code></pre></div>
<pre><code>##    hosp_afl_1   Hospital_name         State            Staffed_beds    
##  150042 :   5   Length:1857        Length:1857        Min.   :    7.0  
##  050471 :   3   Class :character   Class :character   1st Qu.:   72.0  
##  360052 :   3   Mode  :character   Mode  :character   Median :  154.0  
##  360134 :   3                                         Mean   :  232.1  
##  050257 :   2                                         3rd Qu.:  277.0  
##  050380 :   2                                         Max.   :36985.0  
##  (Other):1839                                                          
##  Total_discharges  Patient_days    Gross_patient_revenue    num_phys     
##  Min.   :    1    Min.   :     2   Min.   :    3624      Min.   :   1.0  
##  1st Qu.: 2056    1st Qu.:  7248   1st Qu.:  185397      1st Qu.:  28.0  
##  Median : 5350    Median : 21967   Median :  488683      Median :  69.0  
##  Mean   : 8376    Mean   : 38899   Mean   :  854423      Mean   : 114.4  
##  3rd Qu.:11983    3rd Qu.: 53935   3rd Qu.: 1100914      3rd Qu.: 152.0  
##  Max.   :77757    Max.   :425114   Max.   :14140692      Max.   :1460.0  
##  NA&#39;s   :1        NA&#39;s   :1        NA&#39;s   :9                             
##   female_prop     avg_grad_year   n_specialty    EHR_use 
##  Min.   :0.0000   Min.   :1971   Min.   : 1.00   1:1701  
##  1st Qu.:0.2800   1st Qu.:1994   1st Qu.:12.00   0: 156  
##  Median :0.3600   Median :1996   Median :22.00           
##  Mean   :0.3592   Mean   :1996   Mean   :22.79           
##  3rd Qu.:0.4300   3rd Qu.:1998   3rd Qu.:33.00           
##  Max.   :1.0000   Max.   :2014   Max.   :62.00           
## </code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(hosps[<span class="kw">which</span>(hosps<span class="op">$</span>num_phys <span class="op">&lt;=</span><span class="st"> </span><span class="dv">10</span>),]<span class="op">$</span>EHR_use)</code></pre></div>
<pre><code>## 
##   1   0 
##  52 114</code></pre>
<p>Well, we managed to get about <code>{r} (nrow(hosps)/nrow(hosp_clean))*100</code>% match on the hospitals between the two data sets and the summary statistics on those hospital demographics look a lot nicer and less skewed! Even though we aggregated the physical-level demographics because we didn’t want to just throw away data, we do acknowledge that these physician-level demographics are not really meaningful because they are not representative of the demographics of the hospital. It is unlikely that we had all the physicians information from our <code>hosp_afl</code> for each hospital that matched. (i.e. the 10 physicians we have data on for a hospital may not accurately represent the all practitioners in that hospital) We thought of excluding hospitals with less than 10 practitioners in the data to obtain accurate physician demographics for the hospital, but it would mean cutting down way to much of our limited data. We decided to just focus on the main hospital demographics scraped from the website, and keep the aggregated physician demographics at the exploratory level. Merging with <code>hosp_afl</code> still provided us the main outcome of interest, “EHR_use (the hospital uses the electronic health system)”, calculated as 1 if at least one practitioner in the hospital uses EHR and 0 if none of the practitioners in the hospital uses EHR - that’s why we took the maximum in our code above. Reminder that for practitioners affiliated with hospitals, we assumed that EHR use is the hospital-level adoption and not individual’s. Thus it makes sense that if at least one of the practitioners is recorded in the data as using EHR, we will assume the hospital uses EHR.</p>
</div>
<div id="output-1" class="section level3">
<h3><span class="header-section-number">4.2.3</span> Output</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># clean up intermediate data sets</span>
<span class="kw">rm</span>(hosp_web, hosp_afl)
<span class="co"># hosp_clean will be used later in secondary regional analysis</span>

<span class="co"># permanently save hospital-level analysis dataset to repo</span>
<span class="kw">saveRDS</span>(hosps, <span class="dt">file =</span> <span class="st">&quot;./data/hosps.rds&quot;</span>)</code></pre></div>
<ul>
<li>Again, we are storing the <code>hosps</code> data set as a <code>.rds</code> file in our repo under the <code>/data</code> directory for reproducibility of our analysis since it will be used to analyze the potential effects of hospital demographics on the use of EHR, which is another aspect of our <a href="https://euniceyeh.github.io/EHR-Project/primary.html">Primary Analysis</a>.</li>
<li>This data set will also be subsequently merge with the EHR vendor and product information discussed in the next section to explore hospital demographics by specific types of EHR used.</li>
</ul>
</div>
</div>
<div id="vendors-products-ehr" class="section level2">
<h2><span class="header-section-number">4.3</span> Vendors &amp; Products (EHR)</h2>
<p>Since so many professionals and hospitals across the U.S. have already adopted EHR, we realized that simply looking at the binary outcome of EHR use would be too boring of a project. Thus, we were curious to further explore the demographics of those who do use EHR by the specific types of EHR vendor or product. Fortunately, we were able to find data to support this additional secondary/exploratory analysis.</p>
<div id="sourcemetadata-2" class="section level3">
<h3><span class="header-section-number">4.3.1</span> Source/Metadata</h3>
<p>The <a href="https://dashboard.healthit.gov/datadashboard/documentation/ehr-products-mu-attestation-data-documentation.php">Health IT Dashboard</a> provides certified health IT product data from the ONC Certified Health IT Product List (CHPL) such as the unique vendors, products, and product types of each certified health IT product used as part of the Medicare EHR Incentive Program. We downloaded only the 2016 data set, which also includes unique provider identifiers (NPI), in order to match the <code>EPs</code> data set discussed in the first section of this chapter. As the <a href="https://dashboard.healthit.gov/api/open-api.php?source=onc-data-documentation.csv&amp;data=ehr-products-mu-attestation-data-documentation">metadata</a> explains, a provider in this data set can be either an eligible professional (EP) and eligible hospital (Hospital), as distinguished by the <code>Provider_Type</code> column. Thus, only the <code>Provider_Type == 'EP'</code> records is merged with the subset of <code>EPs</code> who are not affiliated with any hospital, and the <code>Provider_Type == 'Hospital'</code> records is merged with the subset of <code>EPs</code> who are affiliated with a hospital, and therefore directly merged with the combined and cleaned version of the <code>hosp</code> data set discussed in the previous section of this chapter.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EHR &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://dashboard.healthit.gov/datadashboard/data/MU_REPORT_2016.csv&quot;</span>)
<span class="kw">saveRDS</span>(EHR, <span class="st">&quot;./data/EHR_raw.rds&quot;</span>) <span class="co"># saving data for reproducibility</span></code></pre></div>
</div>
<div id="wrangling-2" class="section level3">
<h3><span class="header-section-number">4.3.2</span> Wrangling</h3>
<p>Data structure, you know the drill.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(EHR)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    505914 obs. of  23 variables:
##  $ NPI                             : int  1003000142 1003000522 1003000597 1003000639 1003000902 1003000936 1003000936 1003001256 1003001256 1003001462 ...
##  $ CCN                             : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ Provider_Type                   : Factor w/ 2 levels &quot;EP&quot;,&quot;Hospital&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Business_State_Territory        : Factor w/ 56 levels &quot;Alabama&quot;,&quot;Alaska&quot;,..: 38 11 39 5 17 45 45 6 6 12 ...
##  $ ZIP                             : Factor w/ 11921 levels &quot;&quot;,&quot;00603&quot;,&quot;00612&quot;,..: 5619 4304 9168 10670 5353 3731 3731 10037 10037 4055 ...
##  $ Specialty                       : Factor w/ 288 levels &quot;&quot;,&quot;Acupuncturist&quot;,..: 177 9 279 263 79 27 27 79 79 235 ...
##  $ Hospital_Type                   : Factor w/ 3 levels &quot;&quot;,&quot;Critical Access&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Program_Type                    : Factor w/ 2 levels &quot;Medicare&quot;,&quot;Medicare/Medicaid&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Program_Year                    : int  2016 2016 2016 2016 2016 2016 2016 2016 2016 2016 ...
##  $ Provider_Stage_Number           : Factor w/ 2 levels &quot;Stage 1&quot;,&quot;Stage 2&quot;: 2 2 1 1 2 2 2 2 2 1 ...
##  $ Payment_Year                    : int  3 5 NA NA 5 3 3 5 5 NA ...
##  $ Attestation_Month               : int  2 1 1 2 1 5 5 2 2 3 ...
##  $ Attestation_Year                : int  2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 ...
##  $ MU_Definition_2014              : logi  NA NA NA NA NA NA ...
##  $ Stage_2_Scheduled_2014          : int  0 1 0 0 1 0 0 0 0 0 ...
##  $ EHR_Certification_Number        : Factor w/ 3550 levels &quot;0014E0087U0WV35&quot;,..: 2699 1660 2177 2303 2965 1119 1119 2791 2791 2023 ...
##  $ EHR_Product_CHP_Id              : Factor w/ 2317 levels &quot;14.02.02.1026.A033.01.01.0.170217&quot;,..: 1876 346 1168 1403 2226 136 1747 1403 1876 1004 ...
##  $ Vendor_Name                     : Factor w/ 484 levels &quot;4medica, Inc.&quot;,..: 134 35 338 134 159 170 170 134 134 120 ...
##  $ EHR_Product_Name                : Factor w/ 798 levels &quot;1 Connect BuildYourEMR&quot;,..: 192 42 554 192 81 251 252 192 192 533 ...
##  $ EHR_Product_Version             : Factor w/ 699 levels &quot;1&quot;,&quot;1.0&quot;,&quot;1.0.0&quot;,..: 489 113 385 494 50 549 206 494 489 155 ...
##  $ Product_Classification          : Factor w/ 3 levels &quot;&quot;,&quot;Complete EHR&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ Product_Setting                 : Factor w/ 3 levels &quot;&quot;,&quot;Ambulatory&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ Product_Certification_Edition_Yr: int  2014 2014 2014 2014 2014 2014 2014 2014 2014 2014 ...</code></pre>
<p>There are actually a lot of variables here that are not informative so we can drop them and just focus on a smaller set, i.e. program year would just be 2016 on every row in the data, EHR certification number or CHP ID is at an unnecessary level of detail. Let’s select the important columns and a few potentially interesting variables to summarize by (thus, using <code>distinct</code> instead of <code>select</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EHR_clean &lt;-<span class="st"> </span>EHR <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>(NPI, CCN, Provider_Type, Business_State_Territory, ZIP, Specialty, Hospital_Type, Vendor_Name, EHR_Product_Name, Product_Classification, Product_Setting)
<span class="kw">summary</span>(EHR_clean)</code></pre></div>
<pre><code>##       NPI                 CCN          Provider_Type   
##  Min.   :1.003e+09   Min.   : 10001   EP      :393375  
##  1st Qu.:1.255e+09   1st Qu.:121301   Hospital: 16330  
##  Median :1.508e+09   Median :241361                    
##  Mean   :1.501e+09   Mean   :261394                    
##  3rd Qu.:1.750e+09   3rd Qu.:390179                    
##  Max.   :1.993e+09   Max.   :670114                    
##                      NA&#39;s   :393375                    
##  Business_State_Territory      ZIP        
##  California  : 31692             : 16330  
##  Minnesota   : 24252      55905  : 11278  
##  Florida     : 22664      48109  :  3336  
##  Texas       : 22307      02114  :  3021  
##  Pennsylvania: 20564      32224  :  2818  
##  Michigan    : 19739      60611  :  2521  
##  (Other)     :268487      (Other):370401  
##                                                           Specialty     
##  Family Medicine                                               : 61485  
##  Internal Medicine                                             : 45820  
##  Student in an Organized Health Care Education/Training Program: 17552  
##  Cardiovascular Disease                                        : 17524  
##                                                                : 16330  
##  (Other)                                                       :250764  
##  NA&#39;s                                                          :   230  
##          Hospital_Type                      Vendor_Name    
##                 :393375   Epic Systems Corporation:133637  
##  Critical Access:  3348   Cerner Corporation      : 70367  
##  General        : 12982   Allscripts              : 28067  
##                           athenahealth, Inc.      : 20970  
##                           eClinicalWorks, LLC     : 16354  
##                           GE Healthcare           : 14882  
##                           (Other)                 :125428  
##                                      EHR_Product_Name 
##  EpicCare Ambulatory 2014 Certified EHR Suite: 71207  
##  athenaClinicals                             : 20945  
##  Beacon Oncology 2014 Certified Module       : 16281  
##  eClinicalWorks                              : 16097  
##  NextGen Ambulatory EHR                      : 13616  
##  Powerchart (Clinical)                       : 13293  
##  (Other)                                     :258266  
##   Product_Classification   Product_Setting  
##              : 14690               : 14690  
##  Complete EHR:202827     Ambulatory:325708  
##  Modular EHR :192188     Inpatient : 69307  
##                                             
##                                             
##                                             
## </code></pre>
<p>Observations:</p>
<ul>
<li>There are records of missing CCN (the identifying number for eligible hospitals) and missing hospital type, which matches up with the number of records that are <code>Provider_Type == 'EP'</code>. It makes sense since these variables would not be relevant to an eligible professional (EP), who is not affiliated with any hospital.</li>
<li>There are exactly 16330 records of missing zip codes and blank specialty (specifically <em>not</em> NA’s), and this number matches up with the number of <code>Provider_Type == 'Hospital'</code>.</li>
<li>It sounds like the we just need to split the data into EPs and hospitals since there are enough distinct variables relevant for each type. Then clean each one before merging with their corresponding level of demographics.</li>
</ul>
<p>Split:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># split for EPs</span>
EHR_EPs &lt;-<span class="st"> </span>EHR_clean <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Provider_Type <span class="op">==</span><span class="st"> &#39;EP&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>CCN, <span class="op">-</span>Hospital_Type, <span class="op">-</span>Provider_Type)
<span class="kw">summary</span>(EHR_EPs)</code></pre></div>
<pre><code>##       NPI            Business_State_Territory      ZIP        
##  Min.   :1.003e+09   California  : 30425      55905  : 11278  
##  1st Qu.:1.255e+09   Minnesota   : 23895      48109  :  3336  
##  Median :1.508e+09   Florida     : 21678      02114  :  3021  
##  Mean   :1.501e+09   Texas       : 20941      32224  :  2818  
##  3rd Qu.:1.750e+09   Pennsylvania: 19919      60611  :  2521  
##  Max.   :1.993e+09   Michigan    : 19221      23298  :  2235  
##                      (Other)     :257296      (Other):368166  
##                                                           Specialty     
##  Family Medicine                                               : 61485  
##  Internal Medicine                                             : 45820  
##  Student in an Organized Health Care Education/Training Program: 17552  
##  Cardiovascular Disease                                        : 17524  
##  Obstetrics &amp; Gynecology                                       : 15059  
##  (Other)                                                       :235705  
##  NA&#39;s                                                          :   230  
##                    Vendor_Name    
##  Epic Systems Corporation:131883  
##  Cerner Corporation      : 64893  
##  Allscripts              : 27743  
##  athenahealth, Inc.      : 20929  
##  eClinicalWorks, LLC     : 16345  
##  GE Healthcare           : 14861  
##  (Other)                 :116721  
##                                      EHR_Product_Name 
##  EpicCare Ambulatory 2014 Certified EHR Suite: 71047  
##  athenaClinicals                             : 20928  
##  Beacon Oncology 2014 Certified Module       : 16189  
##  eClinicalWorks                              : 16097  
##  NextGen Ambulatory EHR                      : 13613  
##  Powerchart (Clinical)                       : 12548  
##  (Other)                                     :242953  
##   Product_Classification   Product_Setting  
##              : 14462               : 14462  
##  Complete EHR:200889     Ambulatory:324643  
##  Modular EHR :178024     Inpatient : 54270  
##                                             
##                                             
##                                             
## </code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># check for valid zip codes</span>
EHR_EPs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">nchar</span>(<span class="kw">as.character</span>(ZIP)) <span class="op">&lt;</span><span class="st"> </span><span class="dv">5</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(ZIP) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="kw">n</span>())</code></pre></div>
<pre><code>## # A tibble: 3 x 2
##      ZIP `n()`
##   &lt;fctr&gt; &lt;int&gt;
## 1   1010     1
## 2   EH16     2
## 3   IP28     9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># split for hospitals</span>
EHR_hosps &lt;-<span class="st"> </span>EHR_clean <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Provider_Type <span class="op">==</span><span class="st"> &#39;Hospital&#39;</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>ZIP, <span class="op">-</span>Specialty, <span class="op">-</span>Provider_Type)
<span class="kw">summary</span>(EHR_hosps)</code></pre></div>
<pre><code>##       NPI                 CCN         Business_State_Territory
##  Min.   :1.003e+09   Min.   : 10001   Texas       : 1366      
##  1st Qu.:1.245e+09   1st Qu.:121301   California  : 1267      
##  Median :1.488e+09   Median :241361   Florida     :  986      
##  Mean   :1.495e+09   Mean   :261394   Illinois    :  667      
##  3rd Qu.:1.740e+09   3rd Qu.:390179   Pennsylvania:  645      
##  Max.   :1.993e+09   Max.   :670114   Ohio        :  564      
##                                       (Other)     :10835      
##          Hospital_Type  
##                 :    0  
##  Critical Access: 3348  
##  General        :12982  
##                         
##                         
##                         
##                         
##                                           Vendor_Name  
##  Cerner Corporation                             :5474  
##  Medical Information Technology, Inc. (MEDITECH):2879  
##  Epic Systems Corporation                       :1754  
##  MEDHOST                                        : 653  
##  McKesson                                       : 625  
##  Cerner Health Services, Inc.                   : 525  
##  (Other)                                        :4420  
##                                     EHR_Product_Name
##  HealthSentry                               :  851  
##  Powerchart (Clinical)                      :  745  
##  Powerchart (All CQM&#39;s)                     :  703  
##  P2 Sentinel (Powered by Sensage)           :  580  
##  EpicCare Inpatient 2014 Certified EHR Suite:  565  
##  HealtheLife and Powerchart                 :  552  
##  (Other)                                    :12334  
##   Product_Classification   Product_Setting 
##              :  228                :  228  
##  Complete EHR: 1938      Ambulatory: 1065  
##  Modular EHR :14164      Inpatient :15037  
##                                            
##                                            
##                                            
## </code></pre>
<p>The summaries much look better separately for the two sets. Now we just have to clean up the zip codes for the physician-level EHR’s. Looks like there are only a few records with invalid zip codes. Similar to how we cleaned up the zip codes for <code>EPs</code>, we will match the zip codes with R’s own zip code package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># first remove non-US states, appending DC to list</span>
state_name &lt;-<span class="st"> </span><span class="kw">c</span>(state.name,<span class="st">&quot;District Of Columbia&quot;</span>)
states &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">state_name =</span> state_name, <span class="dt">state_abb =</span> <span class="kw">c</span>(state.abb, <span class="st">&quot;DC&quot;</span>))
EHR_EPs &lt;-<span class="st"> </span>EHR_EPs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(Business_State_Territory <span class="op">%in%</span><span class="st"> </span>state_name)
<span class="kw">length</span>(<span class="kw">unique</span>(EHR_EPs<span class="op">$</span>Business_State_Territory))</code></pre></div>
<pre><code>## [1] 51</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># remove invalid zip codes</span>
EHR_EPs &lt;-<span class="st"> </span>EHR_EPs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(<span class="kw">nchar</span>(<span class="kw">as.character</span>(ZIP)) <span class="op">&gt;=</span><span class="st"> </span><span class="dv">5</span>)

<span class="co"># merge R zip codes</span>
<span class="kw">library</span>(zipcode)
<span class="kw">data</span>(<span class="st">&quot;zipcode&quot;</span>)
EHR_EPs &lt;-<span class="st"> </span>EHR_EPs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">left_join</span>(zipcode, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;ZIP&quot;</span> =<span class="st"> &quot;zip&quot;</span>))</code></pre></div>
<pre><code>## Warning: Column `ZIP`/`zip` joining factor and character vector, coercing
## into character vector</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># check state mismatches</span>
EHR_mismatch &lt;-<span class="st"> </span>EHR_EPs <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">left_join</span>(states, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;state&quot;</span> =<span class="st"> &quot;state_abb&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># need to add in long state names</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Business_State_Territory =</span> <span class="kw">as.character</span>(Business_State_Territory)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(state_name <span class="op">!=</span><span class="st"> </span>Business_State_Territory)</code></pre></div>
<pre><code>## Warning: Column `state`/`state_abb` joining character vector and factor,
## coercing into character vector</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># percent state mismatch</span>
<span class="kw">nrow</span>(EHR_mismatch)<span class="op">/</span><span class="kw">nrow</span>(EHR_EPs)</code></pre></div>
<pre><code>## [1] 0.04492693</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># check which zips are mismatching</span>
EHR_mismatch <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(ZIP, Business_State_Territory, state_name) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">num =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(num)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">head</span>(<span class="dv">8</span>)</code></pre></div>
<pre><code>## # A tibble: 8 x 4
## # Groups:   ZIP, Business_State_Territory [8]
##     ZIP Business_State_Territory   state_name   num
##   &lt;chr&gt;                    &lt;chr&gt;       &lt;fctr&gt; &lt;int&gt;
## 1 51503                 Nebraska         Iowa   120
## 2 99362               Washington       Oregon    83
## 3 54601                Minnesota    Wisconsin    80
## 4 19104               New Jersey Pennsylvania    65
## 5 55905                  Florida    Minnesota    63
## 6 33331                     Ohio      Florida    58
## 7 85259                Minnesota      Arizona    48
## 8 55905                Wisconsin    Minnesota    46</code></pre>
<p>The top 10 mismatches:</p>
<ul>
<li>Zip code 51503 is in Iowa (agrees with zip code package)/bordering Nebraska, but reported as Nebraska which is neighboring Iowa. This may be correct, so we’ll keep Nebraska as reported</li>
<li>Zip code 55905 is in Minnesota, but reported state Florida is not near Minnesota. Since there is likely a typo in either zip or state, we’ll remove this mismatched zip all together</li>
<li>Zip code 54601 is in Wisconsin/bordering Minnesota, but reported as Minnesota which is neighboring Wisconsin. We’ll keep Minnesota as reported</li>
<li>Zip code 33331 is in Florida, which is nowhere near Ohio. Since it is unclear which was the typo, we’ll delete all these mismatches</li>
<li>Zip code 55905 is in Minnesota - found it’s actually Mayo Clinic (along with #2). Wisconsin and Minnesota are bordering each other, so we’ll keep Wisconsin –&gt; in general, if we look at <code>test_mismatch %&gt;% filter(ZIP == &quot;55905&quot;)</code> you will notice that this zip code is incorrectly used for multiple states, possibly meaning there were data entry/quality issues, which validates our decision to clean up the zip codes.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">EHR_zip &lt;-<span class="st"> </span>EHR_EPs <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">left_join</span>(states, <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;state&quot;</span> =<span class="st"> &quot;state_abb&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Business_State_Territory =</span> <span class="kw">as.character</span>(Business_State_Territory)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(
    (state_name <span class="op">==</span><span class="st"> </span>Business_State_Territory) <span class="op">|</span><span class="st"> </span>
<span class="st">    </span>(state_name <span class="op">!=</span><span class="st"> </span>Business_State_Territory <span class="op">&amp;&amp;</span><span class="st"> </span>ZIP <span class="op">==</span><span class="st"> &quot;51503&quot;</span> <span class="op">&amp;&amp;</span><span class="st"> </span>Business_State_Territory <span class="op">==</span><span class="st"> &quot;Nebraska&quot;</span>) <span class="op">|</span>
<span class="st">    </span>(state_name <span class="op">!=</span><span class="st"> </span>Business_State_Territory <span class="op">&amp;&amp;</span><span class="st"> </span>ZIP <span class="op">==</span><span class="st"> &quot;54601&quot;</span> <span class="op">&amp;&amp;</span><span class="st"> </span>Business_State_Territory <span class="op">==</span><span class="st"> &quot;Minnesota&quot;</span>) <span class="op">|</span>
<span class="st">    </span>(state_name <span class="op">!=</span><span class="st"> </span>Business_State_Territory <span class="op">&amp;&amp;</span><span class="st"> </span>ZIP <span class="op">==</span><span class="st"> &quot;55905&quot;</span> <span class="op">&amp;&amp;</span><span class="st"> </span>Business_State_Territory <span class="op">==</span><span class="st"> &quot;Wisconsin&quot;</span>)
    ) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(NPI, Business_State_Territory, ZIP, Specialty, Vendor_Name, EHR_Product_Name, Product_Classification, Product_Setting)</code></pre></div>
<pre><code>## Warning: Column `state`/`state_abb` joining character vector and factor,
## coercing into character vector</code></pre>
<p>We want to inner join with the <code>EPs</code> data set on <code>NPI</code>, which has one row per physician by their unique NPI (one-to-many merge).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># merge with EPs data</span>
EHR_EPs &lt;-<span class="st"> </span><span class="kw">inner_join</span>(EHR_zip, EPs, <span class="dt">by=</span><span class="kw">c</span>(<span class="st">&#39;NPI&#39;</span>=<span class="st">&#39;npi&#39;</span>))
<span class="kw">summary</span>(EHR_EPs)</code></pre></div>
<pre><code>##       NPI            Business_State_Territory     ZIP           
##  Min.   :1.003e+09   Length:24155             Length:24155      
##  1st Qu.:1.165e+09   Class :character         Class :character  
##  Median :1.336e+09   Mode  :character         Mode  :character  
##  Mean   :1.340e+09                                              
##  3rd Qu.:1.509e+09                                              
##  Max.   :1.680e+09                                              
##                                                                 
##            Specialty                                  Vendor_Name   
##  Optometrist    : 4746   Epic Systems Corporation           : 4225  
##  Chiropractor   : 2893   Integrated Practice Solutions, Inc.: 1600  
##  Family Medicine: 2397   Modernizing Medicine, Inc.         : 1544  
##  Ophthalmology  : 1906   NextGen Healthcare                 : 1285  
##  Dermatology    : 1571   GE Healthcare                      : 1048  
##  (Other)        :10638   Mayo Clinic                        : 1035  
##  NA&#39;s           :    4   (Other)                            :13418  
##                                      EHR_Product_Name
##  EpicCare Ambulatory 2014 Certified EHR Suite: 2043  
##  ChiroTouch                                  : 1281  
##  NextGen Ambulatory EHR                      : 1209  
##  athenaClinicals                             : 1019  
##  EMA                                         :  888  
##  eClinicalWorks                              :  732  
##  (Other)                                     :16983  
##   Product_Classification   Product_Setting       cred      
##              :  352                :  352   NA     :15578  
##  Complete EHR:15438      Ambulatory:21513   MD     : 4987  
##  Modular EHR : 8365      Inpatient : 2290   OD     : 1675  
##                                             DC     : 1271  
##                                             DO     :  325  
##                                             DPM    :  290  
##                                             (Other):   29  
##         cty        ehr       gndr          grd_yr    
##  ROCHESTER: 1663   0: 5355   F: 9673   Min.   :1951  
##  LOS ALTOS:  687   1:18800   M:14482   1st Qu.:1985  
##  PALO ALTO:  527             U:    0   Median :1996  
##  NEW YORK :  335                       Mean   :1995  
##  FREMONT  :  276                       3rd Qu.:2005  
##  BOSTON   :  207                       Max.   :2016  
##  (Other)  :20460                                     
##                                      med_sch                   pri_spec   
##  OTHER                                   : 5140   OPTOMETRY        :5155  
##  PALMER COLLEGE CHIROPRACTIC - DAVENPORT :  699   CHIROPRACTIC     :3161  
##  ILLINOIS COLLEGE OF OPTOMETRY AT CHICAGO:  640   FAMILY PRACTICE  :2637  
##  SOUTHERN COLLEGE OF OPTOMETRY           :  572   DERMATOLOGY      :2534  
##  PENNSYLVANIA COLLEGE OF OPTOMETRY       :  538   OPHTHALMOLOGY    :2044  
##  INDIANA UNIVERSITY - SCHOOL OF OPTOMETRY:  420   INTERNAL MEDICINE:1499  
##  (Other)                                 :16146   (Other)          :7125  
##       st                zip              zip.ext             latitude    
##  Length:24155       Length:24155       Length:24155       Min.   :19.53  
##  Class :character   Class :character   Class :character   1st Qu.:34.61  
##  Mode  :character   Mode  :character   Mode  :character   Median :39.04  
##                                                           Mean   :38.31  
##                                                           3rd Qu.:42.13  
##                                                           Max.   :64.85  
##                                                           NA&#39;s   :11     
##    longitude          yrs_grd        locations     
##  Min.   :-159.38   Min.   : 0.00   Min.   : 1.000  
##  1st Qu.:-104.96   1st Qu.:11.00   1st Qu.: 1.000  
##  Median : -90.03   Median :20.00   Median : 1.000  
##  Mean   : -93.52   Mean   :21.31   Mean   : 1.281  
##  3rd Qu.: -80.31   3rd Qu.:31.00   3rd Qu.: 1.000  
##  Max.   : -67.88   Max.   :65.00   Max.   :53.000  
##  NA&#39;s   :11</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># check EHR use (should expect all 1&#39;s or &quot;yes&quot;)</span>
<span class="kw">table</span>(EHR_EPs<span class="op">$</span>ehr)</code></pre></div>
<pre><code>## 
##     0     1 
##  5355 18800</code></pre>
<p>Notice that the <code>ehr</code> column is not all <code>1</code>’s when we expect them to be. This explains why we had so many physicians who fell in the <code>ehr=''</code> category. The physicians whom we have EHR product usage information on did not answer “yes” to EHR use in the original <code>EPs</code> data.</p>
</div>
<div id="output-2" class="section level3">
<h3><span class="header-section-number">4.3.3</span> Output</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">saveRDS</span>(EHR_EPs, <span class="dt">file =</span> <span class="st">&quot;./data/EHR_EPs.rds&quot;</span>)</code></pre></div>
<p>Although the specific product types are too granular and not meaningful enough to clean, we believe that exploring the professional and hospital demographics across vendor types may still be interesting, especially if we focus on the top 10 most popular vendors or classify the smaller local vendors as one group.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="questions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="primary.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/euniceyeh/EHR-Project/edit/master/03-Data.Rmd",
"text": "Edit"
},
"download": ["EHR-Project.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
